# -*- coding: utf-8 -*-
"""gráficos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pgsC1scOP-jQOBGcf3UH2kTcDFCNracd

#Relatório de Análise
"""

# Commented out IPython magic to ensure Python compatibility.
from pickle import FALSE
# %matplotlib inline
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

dados = pd.read_csv('aluguel.csv', sep = ';')
dates = dados.copy()
novo_dado = dates
data_frame = novo_dado.to_json()
df = pd.read_json(data_frame)
df

"""#Gráficos descritivos"""

coracao_do_sistema()

from os import name
def coracao_do_sistema():
  x = df['Valor']
  q1 = x.quantile(.25); q3 = x.quantile(.75)
  q2 = q1 - q3
  ex_sup = q1 - 1.5 * q2; ex_inf = q3 + 1.5 * q2
  selec = (x >= ex_inf) & (x<= ex_sup)
  data_value = df[selec]
    
  y = df['Area']
  qa = y.quantile(.25); qc= y.quantile(.75)
  qb = qc - qa
  extremo_inferior = qa - 1.5 * qb
  extremo_superior = qc + 1.5 * qb
  selecao = (y >= extremo_inferior) & (y <= extremo_superior)
  data_value2 = df[selecao]
  from numpy.core.shape_base import block
  graficos = plt.figure(figsize= (35,35))
  a = graficos.add_subplot(2, 2, 1)
  b = graficos.add_subplot(2, 2, 2)
  c = graficos.add_subplot(2, 2, 3)
  d = graficos.add_subplot(2, 2, 4)
  a.scatter(data_value2['Area'], data_value2['Valor'])
  a.set_title('Valor x area')
  b.hist(data_value['Valor'])
  b.set_title('Histograma dos valores')
  c.hist(data_value2['Area'])
  c.set_title('Histograma da Area dos imoveis')
  resolucao = data_value.groupby('Tipo')['Valor'].mean().round(4)
  resolucao = pd.DataFrame(resolucao).reset_index()
  valor = resolucao['Valor']
  tipo = resolucao['Tipo']
  d.bar(tipo,valor)
  d.set_title('Média de valor por prédio')
if name == 'main':
  coracao_do_sistema()