# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19hbA_EcXdKTGRuFVkPFPDkQkY5e4_g1I

#**Tabela** **de avaliações dos usuários**
"""

import pandas as pd
import matplotlib.pyplot as plt

plam_filmes= pd.read_csv('movies.csv')
plam= pd.read_csv('ratings.csv')
plam

plam.columns= ['usuario','filme','nota','momento']
plam

"""#**Relatório da quantidade de notas**"""

plam['nota'].unique()
plam['nota'].mean()
plam['nota'].value_counts()

plam['nota'].plot(kind='hist')



"""#**Descrição geral da planilha**"""

plam.describe()

import seaborn as table
table.boxplot(plam['nota'])

plam_filmes.columns=['id_do_filme','título','gêneros']
plam_filmes

"""#**Busca por dados especificos em uma** **planilha**"""

film_id_70 = plam.query('filme==70')
plt= plam.query('filme==70')
plam.query('filme == 70')

"""#Gráfico da média de avaliação do filme 70"""

plt.figure(figsize= (15,15))
film_id_70.plot(kind= 'hist')

"""#Média da nota por id do filme"""

grafico_media_por_film = plam.groupby('filme')['nota'].mean()
table1= plam.groupby('filme')['nota'].mean()
dados= pd.DataFrame(table1)
table1.to_frame()

grafico_media_por_film.plot(kind='hist')

plam3= pd.read_csv('tmdb_5000_movies.csv')
pd.read_csv('tmdb_5000_movies.csv')

"""#Número de filmes por linguagem"""

data1= plam3['original_language'].value_counts().to_frame()
xx= plam3['original_language'].value_counts().to_frame().reset_index()
table_x= xx.columns = ['lingua_original', 'total']
xx.columns = ['lingua_original', 'total']
xx

"""#Gráfico de barras sobre o data_frame a cima"""

plt.figure(figsize= (15,15))
table.barplot(data= xx, x= 'lingua_original', y= 'total', palette= 'BrBG')

plam3.groupby('original_language')['original_title'].describe()

"""#diferença da quantidade de títulos em inglês para títulos em outras linguas"""

en= 4505
x= 298
res= en - x
total= 4803
dados= { 
    'línguas': ['ingles', 'demais'],
     'total': [en, x],
    
}
valores= pd.DataFrame(dados)
pd.DataFrame(dados)

plt.figure(figsize= (15,15))
table.barplot(data= valores, x= 'línguas', y='total')

new_table= xx.query("lingua_original !='en'")
pd.DataFrame(new_table)

plt.figure(figsize= (15,15))
table.barplot(data= new_table, y= 'total', x= 'lingua_original', palette= 'BrBG')